//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phirSOFT.MusicTheory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phirSOFT.MusicTheory.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tone(s), {1} semitone(s).
        /// </summary>
        internal static string CommonIntervalFormatFull {
            get {
                return ResourceManager.GetString("CommonIntervalFormatFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} semitone(s).
        /// </summary>
        internal static string CommonIntervalFormatSemitones {
            get {
                return ResourceManager.GetString("CommonIntervalFormatSemitones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} S.
        /// </summary>
        internal static string CommonIntervalFormatSemitonesShort {
            get {
                return ResourceManager.GetString("CommonIntervalFormatSemitonesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tone(s).
        /// </summary>
        internal static string CommonIntervalFormatTones {
            get {
                return ResourceManager.GetString("CommonIntervalFormatTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.
        /// </summary>
        internal static string CommonIntervalFormatTonesShort {
            get {
                return ResourceManager.GetString("CommonIntervalFormatTonesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritone (3 Tones).
        /// </summary>
        internal static string CommonIntervallTritone {
            get {
                return ResourceManager.GetString("CommonIntervallTritone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT.
        /// </summary>
        internal static string CommonIntervallTritoneShort {
            get {
                return ResourceManager.GetString("CommonIntervallTritoneShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized format string &apos;{0}&apos;..
        /// </summary>
        internal static string FormatterUnrecognizedFormat {
            get {
                return ResourceManager.GetString("FormatterUnrecognizedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect unison.
        /// </summary>
        internal static string MmpInterval0 {
            get {
                return ResourceManager.GetString("MmpInterval0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        internal static string MmpInterval0Short {
            get {
                return ResourceManager.GetString("MmpInterval0Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor second.
        /// </summary>
        internal static string MmpInterval1 {
            get {
                return ResourceManager.GetString("MmpInterval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2.
        /// </summary>
        internal static string MmpInterval1Short {
            get {
                return ResourceManager.GetString("MmpInterval1Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major second.
        /// </summary>
        internal static string MmpInterval2 {
            get {
                return ResourceManager.GetString("MmpInterval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2.
        /// </summary>
        internal static string MmpInterval2Short {
            get {
                return ResourceManager.GetString("MmpInterval2Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor third.
        /// </summary>
        internal static string MmpInterval3 {
            get {
                return ResourceManager.GetString("MmpInterval3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m3.
        /// </summary>
        internal static string MmpInterval3Short {
            get {
                return ResourceManager.GetString("MmpInterval3Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major third.
        /// </summary>
        internal static string MmpInterval4 {
            get {
                return ResourceManager.GetString("MmpInterval4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MmpInterval4Short {
            get {
                return ResourceManager.GetString("MmpInterval4Short", resourceCulture);
            }
        }
    }
}
